# Jekyll configuration for DevOps Well-Architected Guide
title: "DevOps Well-Architected Guide"
description: "A community-driven, cloud-agnostic DevOps best-practices framework inspired by the concepts in the GitHub Well-Architected and LeaseWeb maturity model for DevOps."
baseurl: "/devops-well-architected-guide"
url: "https://thecloudexplorers.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .git/
  - .gitignore
  - LICENSE
  - vendor/
  - node_modules/
  - Gemfile.lock

# Repository information
repository: thecloudexplorers/devops-well-architected-guide

# Navigation
header_pages:
  - index.md
  - devops-well-architected-guide/design-principles.md
  - devops-well-architected-guide/checklists.md
  - devops-well-architected-guide/recommendations.md
  - devops-well-architected-guide/how-to-use.md

# Social links (optional)
github_username: thecloudexplorers

# SEO settings
author: The Cloud Explorers
twitter:
  username: thecloudexplorers
  card: summary

# Collections (for future expansion if needed)
collections_dir: collections

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
